### ISSUE TITLE
Reporting user is not set sometimes when a new case is created (app)

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#150]
This leads to a constraint violation on the server an the case not being synchronized

- [x] Reproduce when this happens
- [x] fix it

```
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.2.qualifier): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: null value in column "reportinguser_id" violates not-null constraint
Error Code: 0
Call: INSERT INTO CASES (ID, CASECLASSIFICATION, CHANGEDATE, CONFIRMEDDATE, CREATIONDATE, DESCRIPTION, DISEASE, INVESTIGATEDDATE, INVESTIGATIONSTATUS, MEASLESDOSES, MEASLESVACCINATION, MEASLESVACCINATIONINFOSOURCE, NEGATIVEDATE, NOCASEDATE, POSTIVEDATE, PREGNANT, RECOVEREDDATE, REPORTDATE, SUSPECTDATE, UUID, CASEOFFICER_ID, COMMUNITY_ID, CONTACTOFFICER_ID, DISTRICT_ID, HEALTHFACILITY_ID, PERSON_ID, REGION_ID, REPORTINGUSER_ID, SURVEILLANCEOFFICER_ID, EPIDATA_ID, HOSPITALIZATION_ID, ILLLOCATION_ID, SYMPTOMS_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [33 parameters bound]
Query: InsertObjectQuery(Informant CASE (QLKKSD))
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:879)
	at com.sun.enterprise.container.common.impl.EntityManagerWrapper.flush(EntityManagerWrapper.java:437)
	at de.symeda.sormas.backend.common.AbstractAdoService.ensurePersisted(AbstractAdoService.java:115)
	at sun.reflect.GeneratedMethodAccessor535.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4789)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:369)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4761)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4749)
	at com.sun.ejb.containers.EJBLocalObjectInvocationHandler.invoke(EJBLocalObjectInvocationHandler.java:212)
	... 110 more
```

**Comment by MartinWahnschaffeSymeda** [comment]
This happens when data is dropped. The app keeps the old user which can't be saved when creating a new case or any other object.
