### ISSUE TITLE
IllegalArgumentException: Rumor Manager

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#451]
Caused by: java.lang.IllegalArgumentException: Rumor Manager
	at de.symeda.sormas.backend.caze.CaseService.createUserFilter(CaseService.java:388)
	at sun.reflect.GeneratedMethodAccessor694.invoke(Unknown Source)

**Comment by hzi-braunschweig** [comment]
It only works for the lab user if he is not given multiple roles. But if given multiple role with any role, it crashes

Tom-Aba Daniel (B.Sc MPH)
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124
