### ISSUE TITLE
Test Import function: Error

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#554]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Import of form not possible. creates error and does not generate error report doc
![image](https://user-images.githubusercontent.com/19344651/38369761-be763d00-38e8-11e8-930c-b069daba06e7.png)

**Comment by MartinWahnschaffeSymeda** [comment]
Seems to be related to the following exception:

```
Caused by: javax.persistence.NonUniqueResultException: More than one result was returned from Query.getSingleResult()
	at org.eclipse.persistence.internal.jpa.QueryImpl.throwNonUniqueResultException(QueryImpl.java:980)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getSingleResult(QueryImpl.java:529)
	at org.eclipse.persistence.internal.jpa.EJBQueryImpl.getSingleResult(EJBQueryImpl.java:400)
	at de.symeda.sormas.backend.facility.FacilityService.getByName(FacilityService.java:162)
	at sun.reflect.GeneratedMethodAccessor1835.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4762)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at 
```

**Comment by MartinWahnschaffeSymeda** [comment]
Additional error that is also related to this:

```
Caused by: java.lang.NullPointerException
	at de.symeda.sormas.backend.caze.CaseFacadeEjb.saveCase(CaseFacadeEjb.java:321)
	at sun.reflect.GeneratedMethodAccessor1725.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4762)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:834)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
	at 

Problem is here:
```

		if (caze.getCommunity() != null && !caze.getHealthFacility().getCommunity().equals(caze.getCommunity())) {
			throw new ValidationRuntimeException("Could not find a database entry for the specified health facility in the specified community");
}
```
```

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
I think we should do a hotfix for version 18 first and update sormas.symeda.de with it.

@hzi-braunschweig 
What do you prefer: Should we create a hotfix for version 17 and update sormas.org.ng with it or should we directly update sormas.org.ng with a fixed version 18?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  @MateStrysewskeSym 

Id prefer a fixed version of 18. Thanks

**Comment by MateStrysewskeSym** [comment]
- [ ] rename getByName method for facilities in getHealthFacilityByName and don't include laboratories
